In [1]:
import sqlite3 # py 自带的模块
# sqlite 单机关系型数据库

# 连接到Chinook数据库
conn = sqlite3.connect('chinook.db') # 数据库文件，包含多张表

"""
sqlite vs mysql
- sqlite 单机数据库，嵌入式数据库，和编程语言集成完善，不需要额外安装软件；
- sqlite 默认是一个文件单数据库，mysql 支持 多数据库；
- sqlite 默认是本地使用，并且是单线程使用，不支持远程连接；

vibe coding 推荐 sqlite
"""

# 创建一个游标对象
cursor = conn.cursor()

# 获取数据库中所有表的名称
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
tables

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [2]:
import time
import jwt
import requests
from itertools import combinations
import numpy as np
from tqdm import tqdm

## 数据库解析

In [3]:
import sqlalchemy # orm库， 在编程语言中操作对象，对应对操作数据库

sqlalchemy.__version__

# 借助orm，快速操作底层数据库
# orm是对底层数据库（关系型）的抽象， 表 -》 class， 支持mysql、sqlite、sql server

'2.0.43'

In [4]:
'''数据库解析'''
from typing import Union
import traceback
from sqlalchemy import create_engine, inspect, func, select, Table, MetaData, text # ORM 框架
import pandas as pd

class DBParser:
    '''DBParser 数据库的解析'''
    def __init__(self, db_url:str) -> None:
        '''初始化
        db_url: 数据库链接地址
        mysql: mysql://root:123456@localhost:3306/mydb?charset=utf8mb4
        sqlite: sqlite://chinook.db
        '''

        # 判断数据库类型
        if 'sqlite' in db_url:
            self.db_type = 'sqlite'
        elif 'mysql' in db_url:
            self.db_type = 'mysql'

        # 链接数据库
        self.engine = create_engine(db_url, echo=False)
        self.conn = self.engine.connect()
        self.db_url = db_url

        # 查看表明
        self.inspector = inspect(self.engine)
        self.table_names = self.inspector.get_table_names() # 获取table信息

        self._table_fields = {} # 数据表字段
        self.foreign_keys = [] # 数据库外键
        self._table_sample = {} # 数据表样例

        # 依次对每张表的字段进行统计
        for table_name in self.table_names:
            print("Table ->", table_name)
            self._table_fields[table_name] = {}

            # 累计外键
            self.foreign_keys += [
                {
                    'constrained_table': table_name,
                    'constrained_columns': x['constrained_columns'],
                    'referred_table': x['referred_table'],
                    'referred_columns': x['referred_columns'],
                } for x in self.inspector.get_foreign_keys(table_name)
            ]

            # 获取当前表的字段信息
            table_instance = Table(table_name, MetaData(), autoload_with=self.engine)
            table_columns = self.inspector.get_columns(table_name)
            self._table_fields[table_name] = {x['name']:x for x in table_columns}

            # 对当前字段进行统计
            for column_meta in table_columns:
                # 获取当前字段
                column_instance = getattr(table_instance.columns, column_meta['name'])

                # 统计unique
                query = select(func.count(func.distinct(column_instance)))
                distinct_count = self.conn.execute(query).fetchone()[0]
                self._table_fields[table_name][column_meta['name']]['distinct'] = distinct_count

                # 统计most frequency value
                field_type = self._table_fields[table_name][column_meta['name']]['type']
                field_type = str(field_type)
                if 'text' in field_type.lower() or 'char' in field_type.lower():
                    query = (
                        select(column_instance, func.count().label('count'))
                        .group_by(column_instance)
                        .order_by(func.count().desc())
                        .limit(1)
                    )
                    top1_value = self.conn.execute(query).fetchone()[0]
                    self._table_fields[table_name][column_meta['name']]['mode'] = top1_value

                # 统计missing个数
                query = select(func.count()).filter(column_instance == None)
                nan_count = self.conn.execute(query).fetchone()[0]
                self._table_fields[table_name][column_meta['name']]['nan_count'] = nan_count

                # 统计max
                query = select(func.max(column_instance))
                max_value = self.conn.execute(query).fetchone()[0]
                self._table_fields[table_name][column_meta['name']]['max'] = max_value

                # 统计min
                query = select(func.min(column_instance))
                min_value = self.conn.execute(query).fetchone()[0]
                self._table_fields[table_name][column_meta['name']]['min'] = min_value

                # 任意取值
                query = select(column_instance).limit(10)
                random_value = self.conn.execute(query).all()
                random_value = [x[0] for x in random_value]
                random_value = [str(x) for x in random_value if x is not None]
                random_value = list(set(random_value))
                self._table_fields[table_name][column_meta['name']]['random'] = random_value[:3]

            # 获取表样例（第一行）
            query = select(table_instance)
            self._table_sample[table_name] = pd.DataFrame([self.conn.execute(query).fetchone()])
            self._table_sample[table_name].columns = [x['name'] for x in table_columns]

    def get_table_fields(self, table_name) -> pd.DataFrame:
        '''获取表字段信息'''
        return pd.DataFrame.from_dict(self._table_fields[table_name]).T

    def get_data_relations(self) -> pd.DataFrame:
        '''获取数据库链接信息（主键和外键）'''
        return pd.DataFrame(self.foreign_keys)

    def get_table_sample(self, table_name) -> pd.DataFrame:
        '''获取数据表样例'''
        return self._table_sample[table_name]

    def check_sql(self, sql) -> Union[bool, str]:
        '''检查sql是否合理

        参数
            sql: 待执行句子

        返回: 是否可以运行 报错信息
        '''
        try:
            with self.engine.begin() as conn:  # begin() 会自动提交和关闭
                conn.execute(text(sql))
                        
            return True, 'ok'
        except:
            err_msg = traceback.format_exc()
            return False, err_msg

    def execute_sql(self, sql) -> bool:
        '''运行SQL'''

        with self.engine.begin() as conn:  # begin() 会自动提交和关闭
            result = conn.execute(text(sql))
        
        return list(result)

In [5]:
parser = DBParser('sqlite:///./chinook.db')

Table -> albums
Table -> artists
Table -> customers
Table -> employees
Table -> genres
Table -> invoice_items
Table -> invoices
Table -> media_types
Table -> playlist_track
Table -> playlists
Table -> tracks

In [6]:
parser.get_data_relations()

   constrained_table constrained_columns referred_table referred_columns
0             albums          [ArtistId]        artists       [ArtistId]
1          customers      [SupportRepId]      employees     [EmployeeId]
2          employees         [ReportsTo]      employees     [EmployeeId]
3      invoice_items           [TrackId]         tracks        [TrackId]
4      invoice_items         [InvoiceId]       invoices      [InvoiceId]
5           invoices        [CustomerId]      customers     [CustomerId]
6     playlist_track           [TrackId]         tracks        [TrackId]
7     playlist_track        [PlaylistId]      playlists     [PlaylistId]
8             tracks       [MediaTypeId]    media_types    [MediaTypeId]
9             tracks           [GenreId]         genres        [GenreId]
10            tracks           [AlbumId]         albums        [AlbumId]

In [7]:
parser.get_table_sample("albums")

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1

In [8]:
parser.get_table_fields("genres")

,name,type,nullable,default,primary_key,distinct,nan_count,max,min,random,mode
GenreId,GenreId,INTEGER,False,None,1,25,0,25,1,"[1, 3, 9]",NaN
Name,Name,NVARCHAR(120),True,None,0,25,0,World,Alternative,"[Pop, Rock And Roll, Reggae]",World

In [9]:
parser.get_table_fields(parser.table_names[0])

,name,type,nullable,default,primary_key,distinct,nan_count,max,min,random,mode
AlbumId,AlbumId,INTEGER,False,None,1,347,0,347,1,"[1, 3, 9]",NaN
Title,Title,NVARCHAR(160),False,None,0,347,0,[1997] Black Light Syndrome,...And Justice For All,"[For Those About To Rock We Salute You, Big On...",[1997] Black Light Syndrome
ArtistId,ArtistId,INTEGER,False,None,0,204,0,275,1,"[1, 3, 6]",NaN

In [10]:
parser.check_sql("SELECT COUNT(DISTINCT ArtistId) FROM albums;")

(True, 'ok')

In [11]:
parser.execute_sql("SELECT COUNT(DISTINCT ArtistId) FROM albums;")

[(204,)]

# SQL Agent

In [12]:
import os
import asyncio
# https://bailian.console.aliyun.com/?tab=model#/api-key
os.environ["OPENAI_API_KEY"] = "sk-a7281711aee2443da57a003cd9499933"
os.environ["OPENAI_BASE_URL"] = "https://dashscope.aliyuncs.com/compatible-mode/v1"
from agents import Agent, Runner, AsyncOpenAI, OpenAIChatCompletionsModel

from typing import Annotated
from agents import Agent, Runner, function_tool

@function_tool
def parse_table(tabke_name: Annotated[str, "The table name"]) -> str:
    """Return filed of the given table."""
    return parser.get_table_fields(tabke_name).to_markdown()

# 表结构选择
class SQLTableSelectAgent:
    def __init__(self):
        self.thinking_agent = Agent(
            name="SQL Planer",
            instructions="你是一个专业的SQL专家，请分析在给定的表中哪一个表可以用来回答问题。",
            model="qwen-max",
            tools=[parse_table],
        )

    async def run(self, question: str):
        result = await Runner.run(self.thinking_agent, input=f"用户提问如下：{question}\n\n\n可选择的表格有：{parser.table_names}")
        return result


# sql生成
class SQLGeneratorAgent:
    def 

# 执行sql

# 对执行结果总结 -》 得到输出
class SQLResultSummaryAgent:

In [13]:
import openai
import traceback

client = openai.OpenAI(
    api_key=os.environ["OPENAI_API_KEY"], # https://bailian.console.aliyun.com/?tab=model#/api-key
    base_url=os.environ["OPENAI_BASE_URL"],
)

def ask_gpt(question: str):
    try:
        completion = client.chat.completions.create(
            # 模型列表：https://help.aliyun.com/zh/model-studio/getting-started/models
            model="qwen-plus",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": question},
            ],
        )
        return completion.choices[0].message.content
    except:
        return ""

## 模拟生成问题

In [14]:
# 数据库拓展
# 用户提问的生成
question_prompt = '''你是一个专业的数据库专家，现在需要从用户的角度提问模拟生成一个提问。提问是自然语言，且计数和统计类型的问题，请直接输出具体提问，不需要有其他输出：

表名称：{table_name}

需要提问和统计的字段：{field}

表{table_name}样例如下：
{data_sample_mk}

表{table_name} schema如下：
{data_schema}
'''

answer_prompt = '''你是一个专业的数据库专家，现在需要你结合表{table_name}的信息和提问，生成对应的SQL语句。请直接输出SQL，不需要有其他输出：

表名称：{table_name}

数据表样例如下：
{data_sample_mk}

数据表schema如下：
{data_schema}

提问：{question}
'''

question_rewrite_prompt = '''你是一个专业的数据库专家，现在需要从用户的角度提问模拟生成一个提问。现在需要你将的下面的提问，转换为用户提问的风格。请直接输出提问，不需要有其他输出，不要直接提到表明：

原始问题：{question}

查询的表：{table_name}
'''

answer_rewrite_prompt = '''你是一个专业的数据库专家，将下面的问题回答组织为自然语言。：

原始问题：{question}

执行SQL：{sql}

原始结果：{answer}
'''

company_name_rewrite_prompt = '''将下面的公司的中文缩写名称，如剔除公司名称中的地域信息，或剔除公司名中的有限责任公司等信息。不要输出其他内容，不是英文缩写名称。

原始公司名：{company_name}
'''

In [15]:
gt_qes_answer = []
parser = DBParser('sqlite:///./chinook.db')

# 对于每张表
for table_name in parser.table_names[:1]:
    # 表样例
    data_sample = parser.get_table_sample(table_name)
    data_sample_mk = data_sample.to_markdown()

    # 表格式
    data_schema = parser.get_table_fields(table_name).to_markdown()
    data_fields = list(data_sample.columns)

    # 待选字段
    candidate_fields = list(data_fields) + list(combinations(data_fields, 2)) + list(combinations(data_fields, 3))
    candidate_fields = [' 和 '.join(x) if isinstance(x, tuple) else x for x in candidate_fields]

    # 对每个待选字段生成查询逻辑
    for field in tqdm(candidate_fields[:]):
        # 重试次数
        for _ in range(5):
            # 生成提问
            try:
                input_str = question_prompt.format(table_name=table_name, data_sample_mk=data_sample_mk, data_schema=data_schema, field=field)
                question = ask_gpt(input_str)
                print("question1", question)
                
                # 生成答案SQL
                input_str = answer_prompt.format(table_name=table_name, data_sample_mk=data_sample_mk, data_schema=data_schema, question=question)
                answer = ask_gpt(input_str)
                answer = answer.strip('`').strip('\n').replace('sql\n', '')
                print("answer", answer)

                # 判断SQL是否符合逻辑
                flag, _ = parser.check_sql(answer)
                if not flag:
                    
                    continue

                # 获取SQL答案
                sql_answer = parser.execute_sql(answer)
                if len(sql_answer) > 1:
                    continue
                sql_answer = sql_answer[0]
                sql_answer = ' '.join([str(x) for x in sql_answer])

                # 将提问改写，更加符合用户风格
                input_str = question_rewrite_prompt.format(question=question, table_name=table_name)
                question = ask_gpt(input_str)
                print("question2", question)

                # 将SQL和结果改为为自然语言
                input_str = answer_rewrite_prompt.format(question=question, sql=answer, answer=sql_answer)
                nl_answer = ask_gpt(input_str)
                print("nl_answer", nl_answer)

                gt_qes_answer.append([
                    question, table_name, answer, sql_answer, nl_answer
                ])
                break

            except:
                traceback.print_exc()

    break

Table -> albums
Table -> artists
Table -> customers
Table -> employees
Table -> genres
Table -> invoice_items
Table -> invoices
Table -> media_types
Table -> playlist_track
Table -> playlists
Table -> tracks

  0%|                                                                                        | 0/7 [00:00<?, ?it/s]

question1 albums表中AlbumId字段的总记录数是多少？
answer SELECT COUNT(*) FROM albums;
question2 albums表里一共有多少张专辑？

 14%|███████████▍                                                                    | 1/7 [00:03<00:18,  3.14s/it]

nl_answer albums 表中一共有 347 张专辑。
question1 albums表中Title字段有多少个不同的值？
answer SELECT COUNT(DISTINCT Title) FROM albums;
question2 albums表中Title字段一共有多少个不同的专辑名称？

 29%|██████████████████████▊                                                         | 2/7 [00:06<00:15,  3.01s/it]

nl_answer 在 albums 表中，Title 字段共包含 347 个不同的专辑名称。
question1 albums表中ArtistId字段有多少个不同的值？
answer SELECT COUNT(DISTINCT ArtistId) FROM albums;
question2 albums表里的ArtistId一共有多少个不同的艺术家？

 43%|██████████████████████████████████▎                                             | 3/7 [00:09<00:12,  3.11s/it]

nl_answer 在 `albums` 表中，共有 204 个不同的艺术家（即 `ArtistId` 字段包含 204 个唯一值）。
question1 AlbumId 和 Title 字段的记录总数分别是多少？
answer SELECT COUNT(AlbumId) AS AlbumId_Count, COUNT(Title) AS Title_Count FROM albums;
question2 Albums 表中 AlbumId 和 Title 字段各自有多少条记录？

 57%|█████████████████████████████████████████████▋                                  | 4/7 [00:14<00:11,  3.75s/it]

nl_answer 在 Albums 表中，AlbumId 字段和 Title 字段各自均有 347 条非空记录。这表明该表共包含 347 张专辑，且每张专辑的 AlbumId 和 Title 均已完整填写，不存在任一字段为空值的情况。
question1 AlbumId和ArtistId各自有多少个不同的取值？
answer SELECT COUNT(DISTINCT AlbumId) AS distinct_AlbumId_count, COUNT(DISTINCT ArtistId) AS distinct_ArtistId_count FROM albums;
question2 AlbumId 和 ArtistId 分别有多少个不同的值？

 71%|█████████████████████████████████████████████████████████▏                      | 5/7 [00:18<00:07,  3.97s/it]

nl_answer 在 `albums` 表中，`AlbumId` 共有 347 个不同的取值，而 `ArtistId` 共有 204 个不同的取值。
question1 每个艺术家（ArtistId）发行了多少张专辑（Title）？
answer SELECT ArtistId, COUNT(*) AS album_count
FROM albums
GROUP BY ArtistId;
question1 每个艺术家（ArtistId）发行了多少张专辑（Title）？
answer SELECT ArtistId, COUNT(*) AS album_count FROM albums GROUP BY ArtistId;
question1 每个艺术家（ArtistId）发行了多少张专辑（Title）？
answer SELECT ArtistId, COUNT(*) AS album_count FROM albums GROUP BY ArtistId;
question1 每个艺术家（ArtistId）发行了多少张专辑（Title）？
answer SELECT ArtistId, COUNT(*) AS album_count FROM albums GROUP BY ArtistId;
question1 每个艺术家（ArtistId）发行了多少张专辑（Title）？

 86%|████████████████████████████████████████████████████████████████████▌           | 6/7 [00:26<00:05,  5.47s/it]

answer SELECT ArtistId, COUNT(*) AS album_count FROM albums GROUP BY ArtistId;
question1 专辑表中，每个艺术家（ArtistId）分别有多少张专辑（AlbumId），以及这些专辑的标题（Title）数量分别是多少？
answer SELECT ArtistId, COUNT(AlbumId) AS album_count, COUNT(Title) AS title_count FROM albums GROUP BY ArtistId;
question1 统计albums表中AlbumId、Title和ArtistId这三个字段各自有多少个不同的值？
answer SELECT COUNT(DISTINCT AlbumId) AS AlbumId_count, COUNT(DISTINCT Title) AS Title_count, COUNT(DISTINCT ArtistId) AS ArtistId_count FROM albums;
question2 albums表中AlbumId、Title和ArtistId这三个字段分别有多少个不同的取值？

100%|████████████████████████████████████████████████████████████████████████████████| 7/7 [00:36<00:00,  5.15s/it]

nl_answer 在 `albums` 表中，`AlbumId` 字段有 347 个不同的取值，`Title` 字段也有 347 个不同的取值，而 `ArtistId` 字段则有 204 个不同的取值。这表明每张专辑的 `AlbumId` 和 `Title` 均唯一（即不存在重复的专辑 ID 或重复的专辑标题），而多个专辑可能属于同一位艺术家，因此 `ArtistId` 的不同取值数量（204）少于专辑总数（347）。

In [16]:
gt_qes_answer

[['albums表里一共有多少张专辑？',
  'albums',
  'SELECT COUNT(*) FROM albums;',
  '347',
  'albums 表中一共有 347 张专辑。'],
 ['albums表中Title字段一共有多少个不同的专辑名称？',
  'albums',
  'SELECT COUNT(DISTINCT Title) FROM albums;',
  '347',
  '在 albums 表中，Title 字段共包含 347 个不同的专辑名称。'],
 ['albums表里的ArtistId一共有多少个不同的艺术家？',
  'albums',
  'SELECT COUNT(DISTINCT ArtistId) FROM albums;',
  '204',
  '在 `albums` 表中，共有 204 个不同的艺术家（即 `ArtistId` 字段包含 204 个唯一值）。'],
 ['Albums 表中 AlbumId 和 Title 字段各自有多少条记录？',
  'albums',
  'SELECT COUNT(AlbumId) AS AlbumId_Count, COUNT(Title) AS Title_Count FROM albums;',
  '347 347',
  '在 Albums 表中，AlbumId 字段和 Title 字段各自均有 347 条非空记录。这表明该表共包含 347 张专辑，且每张专辑的 AlbumId 和 Title 均已完整填写，不存在任一字段为空值的情况。'],
 ['AlbumId 和 ArtistId 分别有多少个不同的值？',
  'albums',
  'SELECT COUNT(DISTINCT AlbumId) AS distinct_AlbumId_count, COUNT(DISTINCT ArtistId) AS distinct_ArtistId_count FROM albums;',
  '347 204',
  '在 `albums` 表中，`AlbumId` 共有 347 个不同的取值，而 `ArtistId` 共有 204 个不同的取值。'],
 ['albums表中AlbumId、Title和ArtistId这三个字段分别有多少个不同的取值？',
  'albums',
  'SELECT COUNT(DISTINCT AlbumId) AS AlbumId_count, COUNT(DISTINCT Title) AS Title_count, COUNT(DISTINCT ArtistId) AS ArtistId_count FROM albums;',
  '347 347 204',
  '在 `albums` 表中，`AlbumId` 字段有 347 个不同的取值，`Title` 字段也有 347 个不同的取值，而 `ArtistId` 字段则有 204 个不同的取值。这表明每张专辑的 `AlbumId` 和 `Title` 均唯一（即不存在重复的专辑 ID 或重复的专辑标题），而多个专辑可能属于同一位艺术家，因此 `ArtistId` 的不同取值数量（204）少于专辑总数（347）。']]

In [ ]:
sql agent：
- table select：结合用户提问，选择表； 手动进行推理
- sql generator： 结合选择的提问 + 表 生成sql
- sql execute （sql 是 llm 生成的，可能会报错）：
    parser.check_sql("SELECT COUNT(DISTINCT ArtistId) FROM albums;")
    sql rewrtite： 基于已有sql + 用户输入 + 报错信息
- answer summary：